version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: batuara-db
    environment:
      - POSTGRES_DB=CasaBatuara
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=@5ST73EA4x
    ports:
      - "5432:5432"
    volumes:
      - batuara-db-data-dev:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d CasaBatuara"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  batuara-db-data-dev:
